import React from 'react';
import {
  Activity,
  MapPin,
  Radio,
  ShieldCheck,
  TriangleAlert,
} from 'lucide-react';


const timeLabel = value => {
  if (!value) return '—';

  const date = new Date(value);

  if (Number.isNaN(date.getTime())) {
    return '—';
  }

  return date.toLocaleTimeString([], {
    hour: '2-digit',
    minute: '2-digit',
    second: '2-digit',
  });
};


const percent = value =>
  Number.isFinite(Number(value))
    ? `${(Number(value) * 100).toFixed(0)}%`
    : null;


function EventIcon({ type }) {
  if (type === 'road') {
    return (
      <div className="flex h-9 w-9 items-center justify-center rounded-xl bg-amber-50">
        <TriangleAlert className="h-4 w-4 text-amber-600" />
      </div>
    );
  }

  if (type === 'signal') {
    return (
      <div className="flex h-9 w-9 items-center justify-center rounded-xl bg-violet-50">
        <Radio className="h-4 w-4 text-violet-600" />
      </div>
    );
  }

  return (
    <div className="flex h-9 w-9 items-center justify-center rounded-xl bg-blue-50">
      <Activity className="h-4 w-4 text-blue-600" />
    </div>
  );
}


function EventBadge({ type }) {
  const styles = {
    road: 'border-amber-200 bg-amber-50 text-amber-700',
    traffic: 'border-blue-200 bg-blue-50 text-blue-700',
    signal: 'border-violet-200 bg-violet-50 text-violet-700',
  };

  const labels = {
    road: 'ROAD HAZARD',
    traffic: 'TRAFFIC',
    signal: 'SIGNAL',
  };

  return (
    <span
      className={`rounded-full border px-2 py-0.5 text-[9px] font-extrabold tracking-wider ${
        styles[type] || styles.traffic
      }`}
    >
      {labels[type] || 'EVENT'}
    </span>
  );
}


export function LiveEventStream({ events = [] }) {
  return (
    <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm">

      <div className="flex items-center justify-between border-b border-slate-200 px-5 py-4">
        <div>
          <div className="flex items-center gap-2">
            <Activity className="h-4 w-4 text-blue-600" />

            <h2 className="text-sm font-extrabold text-slate-950">
              Live Event Stream
            </h2>
          </div>

          <p className="mt-1 text-xs text-slate-500">
            Validated intelligence generated by the onboard edge pipeline
          </p>
        </div>

        <div className="flex items-center gap-2 text-[10px] font-bold text-emerald-700">
          <span className="h-2 w-2 animate-pulse rounded-full bg-emerald-500" />
          MONITORING
        </div>
      </div>


      {events.length === 0 ? (
        <div className="flex flex-col items-center justify-center px-5 py-10 text-center">
          <ShieldCheck className="mb-3 h-7 w-7 text-slate-300" />

          <p className="text-sm font-bold text-slate-600">
            Waiting for validated events
          </p>

          <p className="mt-1 max-w-md text-xs leading-relaxed text-slate-400">
            Road hazards appear only after multi-frame confirmation.
            Traffic events appear when congestion or signal state changes.
          </p>
        </div>
      ) : (
        <div className="divide-y divide-slate-100">
          {events.map(event => (
            <div
              key={event.id}
              className="grid grid-cols-[auto_1fr_auto] gap-3 px-5 py-4 transition-colors hover:bg-slate-50"
            >
              <EventIcon type={event.type} />

              <div className="min-w-0">
                <div className="flex flex-wrap items-center gap-2">
                  <EventBadge type={event.type} />

                  <span className="text-[10px] font-semibold text-slate-400">
                    {timeLabel(event.timestamp)}
                  </span>
                </div>

                <p className="mt-1 text-sm font-extrabold text-slate-900">
                  {event.title}
                </p>

                <div className="mt-1 flex flex-wrap gap-x-3 gap-y-1 text-[11px] text-slate-500">
                  <span>
                    {event.busId || 'BUS-104'}
                  </span>

                  <span>
                    {event.cameraId || '—'}
                  </span>

                  {event.confidence !== null &&
                    event.confidence !== undefined && (
                      <span className="font-semibold text-slate-700">
                        {percent(event.confidence)} confidence
                      </span>
                    )}

                  {event.supportFrames && (
                    <span>
                      Confirmed {event.supportFrames} frames
                    </span>
                  )}

                  {event.vehicleCount !== null &&
                    event.vehicleCount !== undefined && (
                      <span>
                        Vehicles {event.vehicleCount}
                      </span>
                    )}
                </div>

                {event.latitude !== undefined &&
                  event.longitude !== undefined && (
                    <div className="mt-2 flex items-center gap-1 text-[10px] text-slate-400">
                      <MapPin className="h-3 w-3" />

                      {Number(event.latitude).toFixed(5)},
                      {' '}
                      {Number(event.longitude).toFixed(5)}
                    </div>
                  )}
              </div>

              <div className="text-right">
                <p className="text-[10px] uppercase tracking-wide text-slate-400">
                  Source
                </p>

                <p className="mt-1 text-[10px] font-bold text-slate-600">
                  EDGE AI
                </p>
              </div>
            </div>
          ))}
        </div>
      )}
    </section>
  );
}